backend/controllers/RbacMenuController.php
<?php

namespace backend\controllers;

/*classes*/
use backend\base\controllers\BaseController;
use Yii;
use yii\db\Exception;
/*active records*/
use common\ActiveRecord\BackendAdmin;
use common\ActiveRecord\RbacMenu;
use common\ActiveRecord\RbacPermission;
/*models*/
use common\models\BackendAdminModel;
use common\models\RbacMenuModel;
use common\models\RbacPermissionModel;

class RbacMenuController extends BaseController
{

    /**
     * @var bool
     */
    public $enableCsrfValidation = false;

    /**
     * 默认action
     * @var string
     */
    public $defaultAction = 'set-admin-menu';

    /**
     * 分配管理员菜单
     */
    public function actionSetAdminMenu()
    {
        $request = Yii::$app->request;
        $adminId = $request->queryParams[ 'adminId' ] ?? Yii::$app->session->get( 'admin_id' , '' );
        $menus = RbacMenuModel::getParentMenusByAdminId( $adminId );
        $admin = BackendAdmin::findOne( $adminId );
        if ( $request->isAjax ) {
            $this->_json();
            $name = $request->queryParams[ 'search' ][ 'term' ] ?? '';
            $limit = $request->queryParams[ 'size' ] ?? $this->limit;
            $query = BackendAdminModel::searchAdminByName( $name , $limit );
            $data = [];
            foreach ( $query as $k => $v ) {
                $tmp = [
                    'id' => $v[ 'id' ] ,
                    'text' => $v[ 'username' ] ,
                ];
                $data[] = $tmp;
            }
            return [ 'code' => 'success' , 'msg' => $data ];
        }
        return $this->render( 'set_admin_menu' , [
            'menus' => $menus ,
            'adminId' => $adminId ,
            //'adminUsername' => Yii::$app->session->get( 'admin_username' , '' ) ,
            'adminUsername' => $admin->username ?? '' ,
        ] );
    }

    /**
     * 异步查询父级菜单
     * @return array
     */
    public function actionAjaxSearchParentMenu()
    {
        $request = Yii::$app->request;
        $this->_json();
        if ( !$request->isGet ) {
            return [];
        }
        $name = $request->queryParams[ 'search' ][ 'term' ] ?? '';
        $limit = $request->queryParams[ 'size' ] ?? $this->limit;
        $adminId = $request->queryParams[ 'adminId' ] ?? '';
        $query = RbacMenuModel::searchParentMenuByName( $name , $limit , $adminId );
        $data = [];
        foreach ( $query as $k => $v ) {
            $tmp = [
                'id' => $v[ 'id' ] ,
                'text' => $v[ 'menu_name' ] ,
            ];
            $data[] = $tmp;
        }
        return [ 'code' => 'success' , 'msg' => $data ];
    }

    /**
     * 删除菜单
     * @return array
     */
    public function actionDeleteMenu()
    {
        $request = Yii::$app->request;
        $this->_json();
        if ( !$request->isPost ) {
            return [ 'code' => 'error' , 'msg' => '没有权限' ];
        }
        $adminId = $request->post( 'adminId' );
        $menuId = $request->post( 'id' );
        $menu = RbacMenu::findOne( [ 'admin_id' => $adminId , 'id' => $menuId ] );
        if ( empty( $menu ) ) {
            return [ 'code' => 'success' , 'msg' => '删除成功' ];
        }
        //如果是父级菜单，则修改子级菜单的父级菜单 id 为 0
        if ( $menu[ 'parent_id' ] == RbacMenuModel::PARENT_ID ) {
            $transaction = Yii::$app->db->beginTransaction();
            try {
                //删除子级菜单 id
                //RbacMenu::updateAll( [ 'parent_id' => RbacMenuModel::PARENT_ID ] , [ 'parent_id' => $menuId ] );
                RbacMenu::deleteAll( [ 'parent_id' => $menuId , 'admin_id' => $adminId ] );
                //删除父级菜单
                RbacMenu::deleteAll( [ 'admin_id' => $adminId , 'id' => $menuId ] );
                $transaction->commit();
                return [ 'code' => 'success' , 'msg' => '删除成功' ];
            } catch ( Exception $e ) {
                $transaction->rollBack();
                return [ 'code' => 'error' , 'msg' => '删除失败' ];
            }
        }
        RbacMenu::deleteAll( [ 'admin_id' => $adminId , 'id' => $menuId ] );
        return [ 'code' => 'success' , 'msg' => '删除成功' ];
    }

    /**
     * 编辑菜单
     * @return string
     */
    public function actionEditMenu()
    {
        $request = Yii::$app->request;
        if ( $request->isPost ) {
            $this->_json();
            $id = $request->post( 'id' );
            $adminId = $request->post( 'adminId' );
            $name = trim( $request->post( 'name' ) );
            $isVisible = $request->post( 'isVisible' );
            $parentMenu = $request->post( 'parentMenu' );
            $permission = $request->post( 'permission' );
            $status = $request->post( 'status' );
            $sort = trim( $request->post( 'sort' ) );
            $menu = RbacMenu::findOne( [ 'id' => $id , 'admin_id' => $adminId ] );
            if ( !$menu ) {
                return [ 'code' => 'error' , 'msg' => '数据不存在.修改失败' ];
            }
            if ( !$name ) {
                return [ 'code' => 'error' , 'msg' => '请填写名称' ];
            }
            if ( mb_strlen( $name ) > 20 ) {
                return [ 'code' => 'error' , 'msg' => '名称不能超过20个字' ];
            }
            if ( $menu->menu_name != $name && RbacMenu::findOne( [ 'menu_name' => $name ] ) ) {
                return [ 'code' => 'error' , 'msg' => '该名称已存在' ];
            }
            if ( !$isVisible && $isVisible != 0 ) {
                return [ 'code' => 'error' , 'msg' => '数据错误.修改失败' ];
            }
            if ( !$status && $status != 0 ) {
                return [ 'code' => 'error' , 'msg' => '数据错误.修改失败' ];
            }
            if ( $isVisible != RbacMenuModel::VISIBLE_DISABLE && $isVisible != RbacMenuModel::VISIBLE_ENABLE ) {
                return [ 'code' => 'error' , 'msg' => '数据错误.修改失败' ];
            }
            if ( $status != RbacMenuModel::STATUS_ENABLE && $status != RbacMenuModel::STATUS_DISABLE ) {
                return [ 'code' => 'error' , 'msg' => '数据错误.修改失败' ];
            }
            if ( $sort ) {
                if ( !is_numeric( $sort ) ) {
                    return [ 'code' => 'error' , 'msg' => '排序值只能是数字' ];
                }
                if ( $sort > 99999999 ) {
                    return [ 'code' => 'error' , 'msg' => '排序值超过最大值，请重新填写' ];
                }
            }
            if ( $parentMenu ) {
                if ( !RbacMenu::findOne( [ 'id' => $parentMenu , 'parent_id' => RbacMenuModel::PARENT_ID , 'status' => RbacMenuModel::STATUS_ENABLE ] ) ) {
                    return [ 'code' => 'error' , 'msg' => '该父级菜单不存在' ];
                }
                $menu->parent_id = $parentMenu;
            }
            if ( $permission ) {
                if ( !RbacPermission::findOne( [ 'id' => $permission , 'status' => RbacPermissionModel::STATUS_ENABLE ] ) ) {
                    return [ 'code' => 'error' , 'msg' => '该权限不存在' ];
                }
                $menu->permission_id = $permission;
            }
            $menu->menu_name = $name;
            $menu->visible = $isVisible;
            $menu->status = $status;
            $menu->sort = $sort;
            return $menu->save()
                ? [ 'code' => 'success' , 'msg' => '修改成功' ]
                : [ 'code' => 'error' , 'msg' => '修改失败' ];
        }
        $id = $request->queryParams[ 'id' ] ?? '';
        $adminId = $request->queryParams[ 'adminId' ] ?? '';
        $menu = RbacMenuModel::getMenuByIdAndAdminId( $id , $adminId );
        return $this->renderAjax( 'edit_admin_menu' , [
            'menu' => $menu ,
            'adminId' => $adminId ,
        ] );
    }

    /**
     * 添加菜单
     * @return array
     */
    public function actionAddAdminMenu()
    {
        $this->_json();
        $request = Yii::$app->request;
        if ( !$request->isPost ) {
            return [ 'code' => 'error' , 'msg' => '没有权限' ];
        }
        $adminId = $request->post( 'adminId' );
        $menuName = $request->post( 'menuName' );
        $isParent = $request->post( 'isParent' );
        $parentMenuId = $request->post( 'parentMenu' );
        $permissionId = $request->post( 'permission' );
        $status = $request->post( 'status' );
        $isVisible = $request->post( 'isVisible' );
        $sort = $request->post( 'sort' );
        $icon = $request->post( 'icon' );
        $admin = BackendAdmin::findOne( $adminId );
        if ( !$admin || empty( $admin ) ) {
            return [ 'code' => 'error' , 'msg' => '没有权限' ];
        }
        if ( !$menuName ) {
            return [ 'code' => 'error' , 'msg' => '请填写名称' ];
        }
        if ( mb_strlen( $menuName ) > 20 ) {
            return [ 'code' => 'error' , 'msg' => '名称不能超过20个字' ];
        }
        if ( !$isParent && $isParent != 0 ) {
            return [ 'code' => 'error' , 'msg' => '请选择是否是父级菜单' ];
        }
        if ( $isParent != RbacMenuModel::IS_PARENT && $isParent != RbacMenuModel::IS_NOT_PARENT ) {
            return [ 'code' => 'error' , 'msg' => '数据错误.添加失败' ];
        }
        if ( $parentMenuId ) {
            if ( empty( RbacMenu::findOne( [ 'id' => $parentMenuId , 'parent_id' => RbacMenuModel::PARENT_ID , 'admin_id' => $adminId ] ) ) ) {
                return [ 'code' => 'error' , 'msg' => '该父级菜单不存在' ];
            }
        } else {
            $parentMenuId = 0;
        }
        if ( $permissionId ) {
            $permission = RbacPermission::findOne( $permissionId );
            if ( empty( $permission ) ) {
                return [ 'code' => 'error' , 'msg' => '该权限不存在' ];
            }
        } else {
            $permissionId = 0;
        }
        if ( !$status && $status != RbacMenuModel::STATUS_DISABLE ) {
            return [ 'code' => 'error' , 'msg' => '请选择状态' ];
        }
        if ( $status != RbacMenuModel::STATUS_DISABLE && $status != RbacMenuModel::STATUS_ENABLE ) {
            return [ 'code' => 'error' , 'msg' => '数据错误.添加失败' ];
        }
        if ( !$isVisible && $isVisible != RbacMenuModel::VISIBLE_DISABLE ) {

backend/views/rbac-menu/edit_admin_menu.php
<?php
use backend\assets\AppAsset;

AppAsset::register( $this );
$this->registerJsFile( '@web/css/adminlte/bower_components/select2/dist/js/select2.full.js' , [ AppAsset::className() , 'depends' => [ 'backend\assets\AppAsset' ] ] );
$this->registerJsFile( '@web/css/adminlte/bower_components/select2/dist/js/i18n/zh-CN.js' , [ AppAsset::className() , 'depends' => [ 'backend\assets\AppAsset' ] ] );
$this->registerCssFile( '@web/css/adminlte/bower_components/select2/dist/css/select2.css' , [ AppAsset::className() , 'depends' => [ 'backend\assets\AppAsset' ] ] );
?>

<?php if ( empty( $menu ) ) : ?>
    <p>没有数据</p>
<?php else : ?>
    <div class="row">
        <div class="col-xs-12">
            <div class="box-body">
                <input type="hidden" id="id" value="<?= $menu[ 'id' ] ?>">
                <input type="hidden" id="admin-id" value="<?= $adminId ?>">
                <div class="form">
                    <div class="form-group">
                        <label>名称</label>
                        <input id="menu_name" type="text" class="form-control" value="<?= $menu[ 'menu_name' ] ?>">
                    </div>
                    <div class="form-group">
                        <label>是否可见</label>
                        <br/>
                        <?php if ( $menu[ 'visible' ] == 1 ) : ?>
                            是<input type="radio" name="is_visible" value="1" checked>
                            否<input type="radio" name="is_visible" value="0">
                        <?php else : ?>
                            是<input type="radio" name="is_visible" value="1">
                            否<input type="radio" name="is_visible" value="0" checked>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label>状态是否可用</label>
                        <br/>
                        <?php if ( $menu[ 'status' ] == 1 ) : ?>
                            是<input type="radio" name="status" value="1" checked>
                            否<input type="radio" name="status" value="0">
                        <?php else : ?>
                            是<input type="radio" name="status" value="1">
                            否<input type="radio" name="status" value="0" checked>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label>父级菜单:
                            <small><?= $menu[ 'menu_name' ] ?></small>
                        </label>
                        <br/>
                        <select aria-hidden="true" tabindex="-1" id="select-parent-menu"
                                class="select2-hidden-accessible"
                                style="width: 100%;" name="parent" disabled>
                            <option value="<?= $menu[ 'id' ] ?>"
                                    selected="selected"><?= $menu[ 'menu_name' ] ?></option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>权限:
                            <small><?= $menu[ 'permission' ][ 'permission_name' ] ?></small>
                        </label>
                        <br/>
                        <select aria-hidden="true" tabindex="-1" id="select-permission"
                                class="select2-hidden-accessible"
                                style="width: 100%;" name="parent">
                            <option value="" selected="selected">不修改则不选择</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>排序</label>
                        <input type="text" class="form-control" value="<?= $menu[ 'sort' ] ?>" id="sort">
                    </div>
                    <div class="form-group">
                        <button type="button" class="btn btn-primary btn-flat btn-sm" id="save">保存</button>
                        <button type="button" class="btn btn-default btn-flat btn-sm" id="cancel">取消</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
    $js = <<<JS
    //ajax query admin menu start
    function ajaxQueryAdminMenu() {
        var adminId = jq("#admin-id").val();
        jq.ajax({
            url : "/rbac-menu/ajax-query-admin-menu" ,
            data : { adminId : adminId } ,
            dataType : "html" ,
            type : "GET" ,
            success : function( data ){
                jq("#ajax-query-container",parent.document).html(data);
            },//success end
        });
    }
    //ajax query admin menu end
        
    jq(document).ready(function(){
        jq.fn.modal.Constructor.prototype.enforceFocus = function () { };
        //select parent menu start
        jq("#select-parent-menu").select2({
            ajax : {
                url : "/rbac-menu/ajax-search-parent-menu" ,
                dataType : "json" ,
                type : "GET" ,
                data : function( term , size ){
                    return {
                        search : term ,
                        size : 10 ,
                    };
                },//data end
                processResults : function( data ){
                    return {
                        results : data.msg ,
                    };
                },//results end
            },
        });
        //select parent menu end
        //select permission start
        jq("#select-permission").select2({
            ajax : {
                url : "/rbac-menu/ajax-search-permission" ,
                dataType : "json" ,
                type : "GET" ,
                data : function( term , size ){
                    return {
                        search : term ,
                        size : 10 ,
                    };
                },//data end
                processResults : function( data ){
                    return {
                        results : data.msg ,
                    };
                },//results end
            },
        });
        //select permission end
        //icheck start
        jq("input[name=\"status\"]").iCheck({
            radioClass : "iradio_square-blue" ,
        });
        jq("input[name=\"is_visible\"]").iCheck({
            radioClass : "iradio_square-blue" ,
        });
        //icheck end
        
        //取消 start
        jq("#cancel").on("click",function(){
            var index = parent.layer.getFrameIndex(window.name); //获取窗口索引
            parent.layer.close(index);
            return true;
        });
        //取消 end
        //保存 start
        jq("#save").on("click",function(){
            var id = jq("#id").val();
            var adminId = jq("#admin-id").val();
            var name = trim(jq("#menu_name").val());
            var isVisible = jq("input[name=\"is_visible\"]:checked").val();
            var status = jq("input[name=\"status\"]:checked").val();
            //var parentMenu = jq("#select-parent-menu").val();
            var permission = jq("#select-permission").val();
            var sort = trim(jq("#sort").val());
            if( name.length <= 0 ){
                layer.msg("请填写名称",{
                    icon : 2 ,
                    time : 1000 ,
                });
                return ;
            }
            if( sort.length > 0 ){
                if( !isNumber(sort) ){
                    layer.msg("排序只能是数字",{
                        icon : 2 ,
                        time : 1000 ,
                    });
                    return ;
                }
            }
            if( !isNumber( isVisible ) ){
                layer.msg( "发生错误.停止执行" , {
                    icon : 2 ,
                    time : 2000 ,
                } );
                return ;
            }
            if( !isNumber( status ) ){
                layer.msg( "发生错误.停止执行" , {
                    icon : 2 ,
                    time : 2000 ,
                } );
                return ;
            }
            jq("#menu_name").val("");
            jq("#sort").val("");
            var index = layer.load(1);
            jq.ajax({
                url : "/rbac-menu/edit-menu" ,
                data : { adminId : adminId , id : id , name : name , isVisible : isVisible , status : status , sort : sort , /*parentMenu : parentMenu ,*/ permission : permission } ,
                dataType : "json" ,
                type : "POST" ,
                success : function( data ){
                    layer.close( index );
                    if( data.code == "success" ){
                        layer.msg("修改成功" , {
                            icon : 1 ,
                            time : 1000 ,
                        });
                        var _index = parent.layer.getFrameIndex(window.name);
                        setTimeout("parent.layer.close(" + index + ");parent.window.location.reload()" , 1100);
                    }
                    if( data.code == "error" ){
                        layer.msg( data.msg , {
                            icon : 2 ,
                            time : 2000 ,
                        } );
                        return ;
                    }
                },//success end
            });
        });
        //保存 end
    });
JS;
    $this->registerJs( $js ) ?>
<?php endif; ?>

backend/views/rbac-menu/edit_admin_parent_menu.php
<?php
use backend\assets\AppAsset;

AppAsset::register( $this );
$this->registerJsFile( '@web/css/adminlte/bower_components/select2/dist/js/select2.full.js' , [ AppAsset::className() , 'depends' => [ 'backend\assets\AppAsset' ] ] );
$this->registerJsFile( '@web/css/adminlte/bower_components/select2/dist/js/i18n/zh-CN.js' , [ AppAsset::className() , 'depends' => [ 'backend\assets\AppAsset' ] ] );
$this->registerCssFile( '@web/css/adminlte/bower_components/select2/dist/css/select2.css' , [ AppAsset::className() , 'depends' => [ 'backend\assets\AppAsset' ] ] );
?>
<?php if ( empty( $menu ) ) : ?>
    <p>没有数据</p>
<?php else : ?>
    <div class="row">
        <div class="col-xs-12">
            <div class="box-body">
                <input type="hidden" id="id" value="<?= $menu[ 'id' ] ?>">
                <input type="hidden" id="admin-id" value="<?= $adminId ?>">
                <div class="form">
                    <div class="form-group">
                        <label>名称</label>
                        <input id="menu_name" type="text" class="form-control" value="<?= $menu[ 'menu_name' ] ?>">
                    </div>
                    <div class="form-group">
                        <label>是否可见</label>
                        <br/>
                        <?php if ( $menu[ 'visible' ] == 1 ) : ?>
                            是<input type="radio" name="is_visible" value="1" checked>
                            否<input type="radio" name="is_visible" value="0">
                        <?php else : ?>
                            是<input type="radio" name="is_visible" value="1">
                            否<input type="radio" name="is_visible" value="0" checked>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label>状态是否可用</label>
                        <br/>
                        <?php if ( $menu[ 'status' ] == 1 ) : ?>
                            是<input type="radio" name="status" value="1" checked>
                            否<input type="radio" name="status" value="0">
                        <?php else : ?>
                            是<input type="radio" name="status" value="1">
                            否<input type="radio" name="status" value="0" checked>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label>权限:
                            <small><?= $menu[ 'permission' ][ 'permission_name' ] ?></small>
                        </label>
                        <br/>
                        <?php if ( $isParent == "false" ) : ?>
                            <select aria-hidden="true" tabindex="-1" id="select-permission"
                                    class="select2-hidden-accessible"
                                    style="width: 100%;" name="parent" disabled>
                                <option value="" selected="selected">父级菜单无需修改</option>
                            </select>
                        <?php else : ?>
                            <select aria-hidden="true" tabindex="-1" id="select-permission"
                                    class="select2-hidden-accessible"
                                    style="width: 100%;" name="parent">
                                <option value="" selected="selected">不修改则不选择</option>
                            </select>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label>排序</label>
                        <input type="text" class="form-control" value="<?= $menu[ 'sort' ] ?>" id="sort">
                    </div>
                    <div class="form-group">
                        <button type="button" class="btn btn-primary btn-flat btn-sm" id="save">保存</button>
                        <button type="button" class="btn btn-default btn-flat btn-sm" id="cancel">取消</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
    $js = <<<JS
    jq.fn.modal.Constructor.prototype.enforceFocus = function () { };
    //icheck start
    jq("input[name=\"status\"]").iCheck({
        radioClass : "iradio_square-blue" ,
    });
    jq("input[name=\"is_visible\"]").iCheck({
        radioClass : "iradio_square-blue" ,
    });
    //icheck end
    //select permission start
    jq("#select-permission").select2({
        ajax : {
            url : "/rbac-menu/ajax-search-permission" ,
            dataType : "json" ,
            type : "GET" ,
            data : function( term , size ){
                return {
                    search : term ,
                    size : 10 ,
                };
            },//data end
            processResults : function( data ){
                return {
                    results : data.msg ,
                };
            },//results end
        },
    });
    //select permission end
    //取消 start
    jq("#cancel").on("click",function(){
        var index = parent.layer.getFrameIndex(window.name); //获取窗口索引
        parent.layer.close(index);
        return true;
    });
    //取消 end
    //保存 start
    jq("#save").on("click",function(){
        var id = jq("#id").val();
        var adminId = jq("#admin-id").val();
        var name = trim(jq("#menu_name").val());
        var isVisible = jq("input[name=\"is_visible\"]:checked").val();
        var status = jq("input[name=\"status\"]:checked").val();
        //var parentMenu = jq("#select-parent-menu").val();
        var permission = jq("#select-permission").val();
        var sort = trim(jq("#sort").val());
        if( name.length <= 0 ){
            layer.msg("请填写名称",{
                icon : 2 ,
                time : 1000 ,
            });
            return ;
        }
        if( sort.length > 0 ){
            if( !isNumber(sort) ){
                layer.msg("排序只能是数字",{
                    icon : 2 ,
                    time : 1000 ,
                });
                return ;
            }
        }
        if( !isNumber( isVisible ) ){
            layer.msg( "发生错误.停止执行" , {
                icon : 2 ,
                time : 2000 ,
            } );
            return ;
        }
        if( !isNumber( status ) ){
            layer.msg( "发生错误.停止执行" , {
                icon : 2 ,
                time : 2000 ,
            } );
            return ;
        }
        jq("#menu_name").val("");
        jq("#sort").val("");
        var index = layer.load(1);
        jq.ajax({
            url : "/rbac-menu/edit-parent-menu" ,
            data : { adminId : adminId , id : id , name : name , isVisible : isVisible , status : status , sort : sort , permission : permission } ,
            dataType : "json" ,
            type : "POST" ,
            success : function( data ){
                layer.close( index );
                if( data.code == "success" ){
                    layer.msg("修改成功" , {
                        icon : 1 ,
                        time : 1000 ,
                    });
                    var _index = parent.layer.getFrameIndex(window.name);
                    setTimeout("parent.layer.close(" + index + ");parent.window.location.reload()" , 1100);
                }
                if( data.code == "error" ){
                    layer.msg( data.msg , {
                        icon : 2 ,
                        time : 2000 ,
                    } );
                    return ;
                }
            },//success end
        });
    });
    //保存 end
JS;
    $this->registerJs( $js );
    ?>
<?php endif; ?>