backend/controllers/BackendAdminController.php
<?php

namespace backend\controllers;

use backend\base\controllers\BaseController;
use Yii;
/*active records*/
use common\ActiveRecord\BackendAdmin;
/*models*/
use common\models\BackendAdminModel;

/**
 * 管理员控制器
 * Class BackendAdminController
 * @package backend\controllers
 */
class BackendAdminController extends BaseController
{

    /**
     * @var bool
     */
    public $enableCsrfValidation = false;

    /**
     * 默认action
     * @var string
     */
    public $defaultAction = 'admin';

    /**
     * 管理员管理页面
     * @return string
     */
    public function actionAdmin()
    {
        $admins = BackendAdminModel::getAdmins( $this->offset , $this->limit );
        return $this->render( 'admin' , [
            'admins' => $admins[ 'data' ] ,
            'count' => $admins[ 'count' ] ,
            'pages' => $admins[ 'pages' ] ,
            'currentPage' => $admins[ 'currentPage' ] ,
            'defaultPageSize' => $this->limit ,
        ] );
    }

    /**
     * 添加管理员
     * @return array
     */
    public function actionAddAdmin()
    {
        $request = Yii::$app->request;
        if ( !$request->isPost ) {
            return [ 'code' => 'error' , 'msg' => '错误的请求方式' ];
        }
        $username = trim( $request->post( 'username' ) );
        $password = trim( $request->post( 'password' ) );
        $status = trim( $request->post( 'status' ) );
        //返回json数据
        $this->_json();
        //验证是否填写用户名
        if ( !$username ) {
            return [ 'code' => 'error' , 'msg' => '请填写账号' ];
        }
        //验证用户名规则
        if ( !preg_match( '/^[_0-9a-zA-Z]*$/' , $username ) ) {
            return [ 'code' => 'error' , 'msg' => '账号只能是数字大小写字母下划线组成' ];
        }
        //验证用户名是否存在
        $sql = 'select `id` from ' . BackendAdmin::tableName() . ' where `username` = :username';
        $query = Yii::$app->db->createCommand( $sql )->bindParam( ':username' , $username )->queryOne();
        if ( $query ) {
            return [ 'code' => 'error' , 'msg' => '该账号已存在' ];
        }
        if ( strlen( $username ) < 6 || strlen( $username ) > 16 ) {
            return [ 'code' => 'error' , 'msg' => '账号不能小于6位或者16位字符' ];
        }
        if ( !$password ) {
            return [ 'code' => 'error' , 'msg' => '请填写密码' ];
        }
        if ( !preg_match( '/^[0-9a-zA-Z]*$/' , $password ) ) {
            return [ 'code' => 'error' , 'msg' => '密码只能是数字大小写字母组成' ];
        }
        //验证账号状态
        if ( $status != BackendAdminModel::STATUS_DISABLE && $status != BackendAdminModel::STATUS_ENABLE ) {
            return [ 'code' => 'error' , 'msg' => '发生错误.失败' ];
        }
        $passwordHash = password_hash( $password , PASSWORD_DEFAULT );
        $execute = Yii::$app->db->createCommand()->insert( BackendAdmin::tableName() , [
            'username' => $username ,
            'password' => $passwordHash ,
            'register_time' => time() ,
            'update_time' => time() ,
            'status' => $status ,
        ] )->execute();
        if ( !$execute ) {
            return [ 'code' => 'error' , 'msg' => '添加失败' ];
        }
        return [ 'code' => 'success' , 'msg' => '' ];
    }

    /**
     * 异步请求管理员数据
     * @return string
     */
    public function actionAjaxQueryAdminPage()
    {
        $admins = [];
        if ( Yii::$app->request->isGet ) {
            $admins = BackendAdminModel::getAdmins( $this->offset , $this->limit );
            //$admins = PermissionModel::getAdmins( $this->offset , $this->limit );
        }
        return $this->renderAjax( '_admins' , [
            'admins' => $admins[ 'data' ] ,
            'offset' => $this->offset ,
            'limit' => $this->limit ,
        ] );
    }

    /**
     * 切换管理员状态
     * @return array
     */
    public function actionToggleAdminStatus()
    {
        $this->_json();
        if ( !Yii::$app->request->isPost ) {
            return [ 'code' => 'error' , 'msg' => '错误的请求的方式' ];
        }
        $status = Yii::$app->request->post( 'status' );
        $id = Yii::$app->request->post( 'id' );
        //验证状态是否正确
        if ( $status != BackendAdminModel::STATUS_DISABLE && $status != BackendAdminModel::STATUS_ENABLE ) {
            return [ 'code' => 'error' , 'msg' => '未知错误，操作失败' ];
        }
        //验证用户是否存在
        $admin = BackendAdmin::findOne( $id );
        if ( empty( $admin ) ) {
            return [ 'code' => 'error' , 'msg' => '该管理员账号不存在' ];
        }
        $admin->status = $status;
        $admin->update_time = time();
        return $admin->save()
            ? [ 'code' => 'success' , 'msg' => '' ]
            : [ 'code' => 'error' , 'msg' => '操作失败' ];
    }

    /**
     * 删除管理员
     * @return array
     */
    public function actionDeleteAdmin()
    {
        $this->_json();
        if ( !Yii::$app->request->isPost ) {
            return [ 'code' => 'error' , 'msg' => '没有权限' ];
        }
        $adminId = Yii::$app->request->post( 'id' );
        return BackendAdminModel::deleteAdmin( $adminId )
            ? [ 'code' => 'success' , 'msg' => '删除成功' ]
            : [ 'code' => 'error' , 'msg' => '删除失败' ];
    }

    /**
     * 编辑管理员
     * @return array|string
     */
    public function actionEditAdmin()
    {
        $request = Yii::$app->request;
        if ( $request->isPost ) {
            $this->_json();
            $id = $request->post( 'id' );
            $username = $request->post( 'username' );
            $password = $request->post( 'password' );
            $status = $request->post( 'status' );
            $admin = BackendAdmin::findOne( $id );
            if ( empty( $admin ) ) {
                return [ 'code' => 'error' , 'msg' => '该管理员不存在' ];
            }
            if ( empty( $username ) ) {
                return [ 'code' => 'error' , 'msg' => '请填写账号' ];
            }
            if ( $admin[ 'username' ] != $username && BackendAdmin::findOne( [ 'username' => $username ] ) ) {
                return [ 'code' => 'error' , 'msg' => '该账号已存在' ];
            }
            if ( mb_strlen( $username ) < 6 ) {
                return [ 'code' => 'error' , 'msg' => '账号不能小于6个字符' ];
            }
            if ( mb_strlen( $username ) > 16 ) {
                return [ 'code' => 'error' , 'msg' => '账号不能大于16个字符' ];
            }
            if ( !preg_match( '/^[_0-9a-zA-Z]*$/' , $username ) ) {
                return [ 'code' => 'error' , 'msg' => '账号只能是大小写字母数字下划线组成' ];
            }
            if ( $password ) {
                if ( mb_strlen( $password ) < 6 ) {
                    return [ 'code' => 'error' , 'msg' => '密码长度不能小于6个字符' ];
                }
                if ( mb_strlen( $password ) > 16 ) {
                    return [ 'code' => 'error' , 'msg' => '密码长度不能大于16个字符' ];
                }
                if ( !preg_match( '/^[0-9a-zA-Z]*$/' , $password ) ) {
                    return [ 'code' => 'error' , 'msg' => '密码只能数大小写字母数字组成' ];
                }
                $admin->password = password_hash( $password , PASSWORD_DEFAULT );
            }
            if ( $status != 0 && empty( $status ) ) {
                return [ 'code' => 'error' , 'msg' => '请选择状态' ];
            }
            if ( $status != BackendAdminModel::STATUS_ENABLE && $status != BackendAdminModel::STATUS_DISABLE ) {
                return [ 'code' > 'error' , 'msg' => '状态值错误' ];
            }
            $admin->username = $username;
            $admin->status = $status;
            $admin->update_time = time();
            return $admin->save()
                ? [ 'code' => 'success' , 'msg' => '保存成功' ]
                : [ 'code' => 'error' , 'msg' => '保存失败' ];
        }
        $id = $request->queryParams[ 'id' ] ?? '';
        $admin = BackendAdmin::findOne( $id );
        return $this->renderAjax( 'edit_admin' , [
            'admin' => $admin ,
        ] );
    }

    /**
     * 展示管理员详情页
     * @return string
     */
    public function actionDetailAdmin()
    {
        $request = Yii::$app->request;
        $id = $request->queryParams[ 'id' ] ?? '';
        $admin = BackendAdmin::findOne( $id );
        return $this->renderAjax( 'detail_admin' , [
            'admin' => $admin ,
        ] );
    }
}

backend/views/backend-admin/_admins.php
<?php
/*ajax query admin page*/
?>
<?php if ( empty( $admins ) ) : ?>
    <div class="row">
        <div class="col-xs-12">
            <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                没有数据
            </p>
        </div>
    </div>
<?php else : ?>
    <div class="row">
        <input type="hidden" id="limit" value="<?= $limit ?>">
        <input type="hidden" id="offset" value="<?= $offset ?>">
        <div class="col-xs-12">
            <table class="table table-bordered table-hover dataTable" id="admins-list"
                   role="grid" aria-describedby="admins-info">
                <thead>
                <tr role="row">
                    <th class="sorting_asc">账号</th>
                    <th class="sorting_asc">状态</th>
                    <th class="sorting_asc">添加时间</th>
                    <th class="sorting_asc">更新时间</th>
                    <th class="sorting_asc">操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ( $admins as $admin ) : ?>
                    <tr role="row">
                        <td>
                            <?= $admin[ 'username' ] ?>
                        </td>
                        <td data-id="<?= $admin[ 'id' ] ?>">
                            <?php if ( $admin[ 'status' ] == 0 ) : ?>
                                <button id="_disable" type="button"
                                        class="btn btn-xs btn-flat btn-default status-action"
                                        data-action="enable">禁用
                                </button>
                            <?php elseif ( $admin[ 'status' ] == 1 ) : ?>
                                <button id="enable" type="button" class="btn btn-xs btn-flat btn-success status-action"
                                        data-action="disable">启用
                                </button>
                            <?php else : ?>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?= date( 'Y-m-d H:i:s' , $admin[ 'register_time' ] ) ?>
                        </td>
                        <td>
                            <?= date( 'Y-m-d H:i:s' , $admin[ 'update_time' ] ) ?>
                        </td>
                        <td>
                            <button class="btn btn-info btn-xs action-btn actions no-margin no-padding"
                                    data-action="detail"
                                    data-id="<?= $admin[ 'id' ] ?>"><span class="fa fa-eye"></span>详情
                            </button>
                            <button class="btn btn-primary btn-xs action-btn actions no-margin no-padding"
                                    data-action="edit" data-id="<?= $admin[ 'id' ] ?>"><span class="fa fa-edit"></span>编辑
                            </button>
                            <button class="btn btn-danger btn-xs action-btn actions no-margin no-padding"
                                    data-action="delete" data-id="<?= $admin[ 'id' ] ?>"><span
                                        class="fa fa-trash"></span>删除
                            </button>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif ?>
<?php
$js = <<<JS
jq(document).ready(function(){
    //切换状态 start
    jq(".status-action").click(function(){
        var action = jq(this).attr("data-action");
        var dataAction = jq(this).attr("data-action");
        var id = jq(this).parent().attr("data-id");
        var offset = jq("#offset").val();
        var limit = jq("#limit").val();
        if( dataAction == "disable" ){
            status = 0;
        }
        if( dataAction == "enable" ){
            status = 1;
        }
        var index = layer.load(1);
        jq.ajax({
            url : "/backend-admin/toggle-admin-status" ,
            data : { status : status , id : id } ,
            dataType : "json" ,
            type : "POST" ,
            success : function( data ){
                layer.close(index);
                if( data.code == "success" ){
                    layer.msg("操作成功",{
                        icon : 1 ,
                        time : 1000 ,
                    });
                    setTimeout(function(){
                        var searchStr = window.location.search;
                        var offset = jq("#offset").val();
                        if(searchStr.match(/offset/)){
                            window.location.href = replaceParamVal("offset",offset);
                        }else{
                            if(searchStr.length == 0){
                                url = "?offset=" + offset;
                            }else{
                                url = searchStr + "&offset=" + offset;
                            }
                            window.location.href = url;
                        }
                    },1100);
                }
                if( data.code == "error" ){
                    layer.msg(data.msg,{
                        icon : 2 ,
                        time : 1000 ,
                    });
                }
            },//success end
        });
    });
    //切换状态 end
    //操作 start
    jq(".actions").click(function(){
        var action = jq(this).attr("data-action");
        var id = jq(this).attr("data-id");
        //详情
        if( action == "detail" ){
            layer.open({
                type : 2 ,
                title : "查看详情" ,
                shadeClose : true ,
                shade : 0.8 ,
                area : ["700px","600px"] ,
                content : "/backend-admin/detail-admin?id=" + id ,
            });
        }
        //编辑
        if( action == "edit" ){
            layer.open({
                type : 2 ,
                title : "编辑" ,
                shadeClose : false ,
                shade : 0.8 ,
                area : ["300px","400px"],
                content : "/backend-admin/edit-admin?id=" + id ,
            });
        }
        //删除
        if( action == "delete" ){
            layer.msg("确定删除?",{
                btn : ["确定","取消"] ,
                time : 0 ,
                yes : function( index ){
                    layer.close( index );
                    var _index = layer.load(1);
                    jq.ajax({
                        url : "/backend-admin/delete-admin" ,
                        data : { id : id } ,
                        type : "POST" ,
                        dataType : "json" ,
                        success : function( data ){
                            layer.close( _index );
                            var offset = jq("#offset").val();
                            if( data.code == "success" ){
                                layer.msg("删除成功" , {
                                    icon : 1 ,
                                    time : 1000 ,
                                });
                                iReloadPage( offset , 1100 );
                            }
                        },//success end
                    });
                },//yes end
            });
        }
    });
    //操作 end
});
JS;
$this->registerJs( $js );
?>

backend/views/backend-admin/detail_admin.php
<?php
use backend\assets\AppAsset;

AppAsset::register( $this );
?>
<?php if ( empty( $admin ) ) : ?>
    <p>没有数据</p>
<?php else : ?>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1" style="margin-top:10px;">
            <table class="table table-bordered">
                <tbody>
                <tr role="row">
                    <td style="width: 20%;" class="text-right"><b>管理员账号</b></td>
                    <td style="width: 80%;"><?= $admin[ 'username' ] ?></td>
                </tr>
                <tr>
                    <td style="width: 20%;" class="text-right"><b>注册时间</b></td>
                    <td style="width: 80%;"><?= date( 'Y-m-d H:i:s' , $admin[ 'register_time' ] ) ?></td>
                </tr>
                <tr>
                    <td style="width: 20%;" class="text-right"><b>更新数据时间</b></td>
                    <td style="width: 80%;"><?= date( 'Y-m-d H:i:s' , $admin[ 'update_time' ] ) ?></td>
                </tr>
                <tr>
                    <td style="width: 20%;" class="text-right"><b>账号状态</b></td>
                    <td>
                        <?php if ( $admin[ 'status' ] == 1 ) : ?>
                            <span class="label label-success">正常</span>
                        <?php else : ?>
                            <span class="label label-warning">禁用</span>
                        <?php endif; ?>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
<?php endif; ?>

backend/views/backend-admin/edit_admin.php
<?php
use backend\assets\AppAsset;

AppAsset::register( $this );
?>
<?php if ( empty( $admin ) ): ?>
    <p>没有数据</p>
<?php else : ?>
    <div class="row">
        <input type="hidden" id="edit-id" value="<?= $admin[ 'id' ] ?>">
        <div class="col-xs-12">
            <div class="box-body">
                <div class="form">
                    <div class="form-group">
                        <label>管理员账号</label>
                        <input type="text" id="username" class="form-control" value="<?= $admin[ 'username' ] ?>">
                    </div>
                    <div class="form-group">
                        <label>密码</label>
                        <input type="password" id="password" value="" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>重复密码</label>
                        <input type="password" id="repeat-password" value="" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>状态</label>
                        <br/>
                        <?php if ( $admin[ 'status' ] == 1 ) : ?>
                            启用<input type="radio" name="status" value="1" checked>
                            禁用<input type="radio" name="status" value="0">
                        <?php else : ?>
                            启用<input type="radio" name="status" value="1">
                            禁用<input type="radio" name="status" value="0" checked>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <button type="button" class="btn btn-primary btn-flat btn-sm" id="edit-save">保存</button>
                        <button type="button" class="btn btn-default btn-flat btn-sm" id="edit-cancel">取消</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
    $js = <<<JS
    jq(document).ready(function(){
        //取消
        jq("#edit-cancel").on("click",function(){
            var index = parent.layer.getFrameIndex(window.name); //获取窗口索引
            parent.layer.close(index);
            return true;
        });
        //取消
        
        //保存
        jq("#edit-save").on("click" , function(){
            var id = jq("#edit-id").val();
            var username = trim(jq("#username").val());
            var password = trim(jq("#password").val());
            var repeatPassword = trim(jq("#repeat-password").val());
            var status = jq("input[name=\"status\"]:checked").val();
            if(trim(username).length <= 0){
                layer.msg("请填写账号" , {
                    icon : 2 ,
                    time : 2000 ,
                });
                return ;
            }
            if( username.length > 16 ){
                layer.msg("账号不能超过16个字符",{
                    icon : 2 ,
                    time : 2000 ,
                });
                return ;
            }
            if(trim(password).length > 0){
                if( password.length < 6 ){
                    layer.msg("密码长度不能小于6个字符",{
                        icon : 2 ,
                        time : 2000 ,
                    });
                    return ;
                }
                if( password.length > 16 ){
                    layer.msg("密码长度不能超过16个字符",{
                        icon : 2 ,
                        time : 2000 ,
                    });
                    return ;
                }
                var preg = /^[0-9a-zA-Z]*$/;
                if(!preg.test(password)){
                //if( !password.test(/^[0-9a-zA-Z_]*$/)){
                    layer.msg("密码只能是大小写字母数字下划线组成",{
                        icon : 2 ,
                        time : 2000 ,
                    });
                    return ;
                }
            }
            if( password != repeatPassword ){
                layer.msg("两次密码不一致",{
                    icon : 2,
                    time : 2000 ,
                });
                return ;
            }
            if( isNull(status) ){
                layer.msg("请选择状态",{
                    icon : 2 ,
                    time : 2000 ,
                });
                return ;
            }
            jq("#username,#password,#repeat-password").val("");
            var index = layer.load(1);
            jq.ajax({
                url : "edit-admin" ,
                data : { id : id , username : username , password : password , repeatPassword : repeatPassword , status : status } ,
                dataType : "json" ,
                type : "POST" ,
                success : function(data){
                    layer.close(index);
                    if(data.code == "success" ){
                        layer.msg("保存成功",{
                            icon : 1 ,
                            time : 1000 ,
                        });
                        var index = parent.layer.getFrameIndex(window.name); //获取窗口索引
                        setTimeout("parent.layer.close(" + index + ");window.location.reload()" , 1100);
                        return ;
                    }
                    if(data.code == "error" ){
                        layer.msg( data.msg , {
                            icon : 2 ,
                            time : 2000 ,
                        });
                    }
                },//success end
            });
        });
        //保存
        //icheck start
        jq("input[name=\"status\"]").iCheck({
            radioClass : "iradio_square-blue" ,
        });
        //icheck end
    });
    jq("input[name=\"status\"]").iCheck({
        radioClass : "iradio_square-blue" ,
    });
JS;
    $this->registerJs( $js );
    ?>
<?php endif; ?>