backend/controllers/WebController.php
<?php

namespace backend\controllers;

use common\models\RbacRoleModel;
use yii\web\Controller;
use Yii;
use common\ActiveRecord\BackendAdmin;
use common\services\verifyCodeClass;

class WebController extends Controller
{

    /**
     * 不使用布局文件
     * @var bool
     */
    public $layout = false;

    /**
     * 初始化函数
     */
    public function init()
    {
        $this->enableCsrfValidation = false;
    }

    /**
     * 登录
     * @return string
     */
    public function actionLogin()
    {
        $request = Yii::$app->request;
        $session = Yii::$app->session;
        if ( $session->has( 'admin_id' ) ) {
            return $this->redirect( [ Yii::$app->defaultRoute ] );
        }
        if ( $request->isPost ) {
            $post = $request->post();
            $username = $post[ 'username' ];
            $password = $post[ 'password' ];
            $code = $post[ 'code' ];
            if ( !$code ) {
                return json_encode( [ 'code' => 'fail' , 'msg' => '请输入验证码' ] );
            }
            $_code = Yii::$app->redis->get( verifyCodeClass::REDIS_KEY_PREFIX . $code );
            if ( $_code != $code ) {
                return json_encode( [ 'code' => 'fail' , 'msg' => '验证码错误' ] );
            }
            $admin = BackendAdmin::findOne( [ 'username' => $username ] );
            if ( !$admin || empty( $admin ) ) {
                return json_encode( [ 'code' => 'fail' , 'msg' => '账号密码错误' ] );
            }
            if ( !password_verify( $password , $admin->password ) ) {
                return json_encode( [ 'code' => 'fail' , 'msg' => '账号密码错误' ] );
            }
            if ( $admin->status == RbacRoleModel::STATUS_DISABLE ) {
                return json_encode( [ 'code' => 'fail' , 'msg' => '该账号暂时不可用' ] );
            }
            $loginData = [
                'admin_id' => $admin->id ,
                'admin_username' => $admin->username ,
                'admin_register_time' => $admin->register_time ,
                'admin_update_time' => $admin->update_time
            ];
            $this->setLoginData( $loginData );
            return json_encode( [ 'code' => 'success' , 'msg' => '登录成功' ] );
        }
        $defaultRoute = Yii::$app->defaultRoute;
        $verifyCodeImage = $this->actionVerifyCodeImage();
        return $this->render( 'login' , [
            'defaultRoute' => $defaultRoute ,
            'verifyCodeImage' => $verifyCodeImage ,
        ] );
    }

    /**
     * 设置登录数据
     *
     * @param array $data
     */
    private function setLoginData( $data = [] )
    {
        $session = Yii::$app->session;
        $session->set( 'admin_id' , $data[ 'admin_id' ] );
        $session->set( 'admin_username' , $data[ 'admin_username' ] );
        Yii::$app->redis->hmset( 'admin_info' , 'admin_id' , $data[ 'admin_id' ] , 'admin_username' , $data[ 'admin_username' ] , 'admin_register_time' , $data[ 'admin_register_time' ] , 'admin_update_time' , $data[ 'admin_update_time' ] );
    }

    /**
     * 删除登录session数据
     */
    private function unsetLoginData()
    {
        //unset session
        $session = Yii::$app->session;
        $session->destroy();
        //delete redis
        $redis = Yii::$app->redis;
        $redis->del( 'admin_info' );
    }

    /**
     * 退出登录
     *
     */
    public function actionLogout()
    {
        $this->unsetLoginData();
        header( 'Location:/web/login' );
        exit();
    }

    /**
     * 获取验证码图片
     * @return string
     */
    public function actionVerifyCodeImage()
    {
        $imgObj = new verifyCodeClass();
        $imgAddress = $imgObj->getImage();
        $verifyCode = $imgObj->getCode();
        Yii::$app->redis->set( verifyCodeClass::REDIS_KEY_PREFIX . $verifyCode , $verifyCode );
        return Yii::$app->params[ 'webBaseUrl' ] . '/' . Yii::$app->params[ 'verifyCodeImageDir' ] . '/' . $imgAddress;
    }
}

backend/views/web/ajax_permission_deny.php
<p class="text-muted well well-sm no-shadow text-red" style="margin-top: 10px;">
    403 Error.Permission Deny
</p>

backend/views/web/login.php
<!DOCTYPE html>
<html lang="en">
<meta charset="utf8">
<head>
    <title>登录</title>
    <link rel="stylesheet" href="/css/adminlte/bower_components/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="/css/adminlte/dist/css/AdminLTE.css"/>
    <script src="/css/adminlte/bower_components/jquery/dist/jquery.js"></script>
    <script src="/js/layer/layer.js"></script>
</head>
<body class="hold-transition login-page">
<input type="hidden" id="default-route" value="<?= $defaultRoute ?>">
<div class="login-box">
    <div class="login-box-body">
        <p class="login-box-msg">登录管理后台</p>
        <div class="form-group has-feedback">
            <input id="username" class="form-control" placeholder="管理员账号" type="text">
        </div>
        <div class="form-group has-feedback">
            <input id="password" class="form-control" placeholder="管理员密码" type="password">
        </div>
        <div class="row">
            <div class="col-xs-6">
                <div class="form-group">
                    <input type="text" class="form-control" id="code" placeholder="验证码">
                </div>
            </div>
            <div class="col-xs-4">
                <div class="form-group">
                    <img src="<?= $verifyCodeImage ?>" id="refresh-code" class="form-control"
                         style="border:0px;width:100px;cursor:pointer"/>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <button id="login" type="button" class="btn btn-primary btn-block btn-flat">登录</button>
            </div>
        </div>
    </div>
</div>
</body>
</html>
<script>
    var jq = $;

    jq(document).ready(function () {
        //默认路由
        var defaultRoute = jq("#default-route").val();
        //登录 start
        jq("#login").click(function () {
            var username = jq("#username").val();
            var password = jq("#password").val();
            var code = jq("#code").val();
            if (username.length == 0) {
                layer.tips('请输入账号', '#username');
                return;
            }
            if (password.length == 0) {
                layer.tips('请输入密码', '#password');
                return;
            }
            if (code.length == 0) {
                layer.tips("请输入验证码", '#code')
                return;
            }
            jq("#username,#password").val("");
            var _index = layer.load(1);
            jq.ajax({
                url: "/web/login",
                data: {username: username, password: password, code: code},
                dataType: "json",
                type: "POST",
                success: function (data) {
                    console.log(data);
                    layer.close(_index);
                    if (data.code == 'fail') {
                        layer.msg(data.msg, {
                            icon: 2,
                            time: 1000,
                        });
                        setTimeout("window.location.reload()", 1100);
                        return;
                    }
                    if (data.code == 'success') {
                        layer.msg(data.msg, {
                            icon: 1,
                            time: 1000,
                        });
                        setTimeout("window.location.href=\"/" + defaultRoute + "\"", 1100);
                    }
                },
            });
        });
        //登录 end
        //刷新验证码图片 start
        jq("#refresh-code").on("click", function () {
            jq.ajax({
                url: "/web/verify-code-image",
                data: {},
                dataType: "text",
                type: "GET",
                success: function (data) {
                    var _src = data + "?rnd=" + Math.random()
                    jq("#refresh-code").attr("src", _src);
                }
            });
        });
        //刷新验证码图片 end
    });
</script>

backend/views/web/permission_deny.php
<section class="content">
    <div class="error-page">
        <h2 class="headline text-danger">403</h2>

        <div class="error-content">
            <h3><i class="fa fa-warning text-danger"></i>You have no permission to request this page.</h3>

            <p>
                You have <b class="text-yellow">NO PERMISSION</b> to request this page.Please contact with your
                administrator.<a href="javascript:history.back()">Click to go back</a>
            </p>

        </div>
        <!-- /.error-content -->
    </div>
</section>